In [2]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

In [21]:
data = {
    "name" : ["Falcon Heavy", "Falcon 9", "Starship Super Heavy", "Dragon"],
    "flights" : [11, 600,11,30],
    "rating" : [4,5,3,3]
}

df = pd.DataFrame(data=data, index=["alpha", "beta", "gamma", "delta"])
df

                       name  flights  rating
alpha          Falcon Heavy       11       4
beta               Falcon 9      600       5
gamma  Starship Super Heavy       11       3
delta                Dragon       30       3

In [22]:
df.head() # prints first 5 rows

                       name  flights  rating
alpha          Falcon Heavy       11       4
beta               Falcon 9      600       5
gamma  Starship Super Heavy       11       3
delta                Dragon       30       3

In [23]:
df.info() # prints the data types for all columns

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, alpha to delta
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     4 non-null      object
 1   flights  4 non-null      int64
 2   rating   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 128.0+ bytes

In [24]:
df.describe() # gives stats for numerical cols

          flights    rating
count    4.000000  4.000000
mean   163.000000  3.750000
std    291.470982  0.957427
min     11.000000  3.000000
25%     11.000000  3.000000
50%     20.500000  3.500000
75%    172.500000  4.250000
max    600.000000  5.000000

In [25]:
# accessing cols

df["flights"]

alpha     11
beta     600
gamma     11
delta     30
Name: flights, dtype: int64

In [26]:
df[["name", "rating"]]

                       name  rating
alpha          Falcon Heavy       4
beta               Falcon 9       5
gamma  Starship Super Heavy       3
delta                Dragon       3

In [ ]:
# loc ---> selecting row by label

df.loc["gamma"]

name       Starship Super Heavy
flights                      11
rating                        3
Name: gamma, dtype: object

In [28]:
# iloc ---> selecting row by integer idx

df.iloc[0]

name       Falcon Heavy
flights              11
rating                4
Name: alpha, dtype: object

In [30]:
# filtering data from the data frame
df[df["rating"] > 3]

               name  flights  rating
alpha  Falcon Heavy       11       4
beta       Falcon 9      600       5

In [32]:
# adding and modifying cols

df["human rated"] = df["rating"] >= 4
df.head()

                       name  flights  rating  human rated
alpha          Falcon Heavy       11       4         True
beta               Falcon 9      600       5         True
gamma  Starship Super Heavy       11       3        False
delta                Dragon       30       3        False

In [33]:
# grouping and aggregation

df.groupby("human rated")["rating"].mean()

human rated
False    3.0
True     4.5
Name: rating, dtype: float64